### ISSUE TITLE
C2873 While building project

### ISSUE THREAD

**Issue by 17steen** [SeanOMik/BaseSleepyDiscordProject#1]
Hello
We tried this on two different computers and both got this error on this file, not really sure of what it is.
`Severity	Code	Description	Project	File	Line	Suppression State
Error	C2873	'std::unordered_map<SleepyDiscord::Snowflake<SleepyDiscord::Server>::RawType,_Type,std::hash<SleepyDiscord::Snowflake<SleepyDiscord::Server>::RawType>,std::equal_to<SleepyDiscord::Snowflake<SleepyDiscord::Server>::RawType>,std::allocator<std::pair<const SleepyDiscord::Snowflake<SleepyDiscord::Server>::RawType,_Type>>>': symbol cannot be used in a using-declaration	D:\CPP\BaseSleepyDiscordProject\out\build\x64-Debug\BaseSleepyDiscordProject	D:\CPP\BaseSleepyDiscordProject\thirdparty\sleepy-discord\include\sleepy_discord\cache.h	16	
`

**Comment by SeanOMik** [comment]
Thanks for making the pull request, but I've actually stopped using SleepyDiscord. SleepyDiscord is slow, single threaded, and later out in a weird way. The single threaded issue is massive. If you make a command that has to wait for 5 seconds for example, the command will freeze the entire bot, causing the bot the miss events.

Those issues caused me to create my own library, [DisC++](https://github.com/DisCPP/DisCPP). I would recommend you switching to DisC++ as it's faster, multithreaded, and has a command handler built into it. We also have a discord that you can join for support. Here's an [invite](https://discord.gg/UrTex5Y) link.

Tell me if you decide to switch or not.

**Comment by 17steen** [comment]
Nice, my real issue being finding a library in C++, we can consider this solved. Thanks

**Comment by SeanOMik** [comment]
Awesome, just follow the tutorial in the readme and if you encounter any issues I can help on Discord or by you making a GitHub issue on the [DisC++](https://github.com/DisCPP/DisCPP) GitHub.
